# Generated by Django 4.1.7 on 2023-03-01 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAsset0',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_name', models.CharField(help_text='E.g Samsung P3 laptop,', max_length=40)),
                ('available', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Write Your role in the company', max_length=40)),
                ('dob', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone_number', models.IntegerField()),
                ('id_number', models.IntegerField()),
                ('kra_pin', models.IntegerField()),
                ('time_off_start', models.DateField()),
                ('time_off_end', models.DateField()),
                ('on_leave', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer0',
            fields=[
                ('Employer_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(help_text='Write the company name and your current position', max_length=40)),
                ('company', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.IntegerField()),
                ('employee_number', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInventory0',
            fields=[
                ('inventory_id', models.AutoField(primary_key=True, serialize=False)),
                ('taking', models.DateField()),
                ('returning', models.DateField()),
                ('returned', models.BooleanField(default=False, help_text='tick this if an item in the inventory has been returned successfully.')),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_system.companyasset0')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
