# Generated by Django 4.1.7 on 2023-03-01 22:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyAsset0',
            new_name='CompanyAsset',
        ),
        migrations.RenameModel(
            old_name='CompanyInventory0',
            new_name='CompanyInventory',
        ),
        migrations.RenameModel(
            old_name='Employer0',
            new_name='Employer',
        ),
        migrations.RenameModel(
            old_name='Profile0',
            new_name='Profile',
        ),
    ]
