# Generated by Django 4.1.7 on 2023-03-01 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_system', '0002_rename_companyasset0_companyasset_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Employee',
        ),
    ]
