# Generated by Django 4.1.7 on 2023-03-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0003_rename_profile_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Employer',
            field=models.OneToOneField(default=2014, on_delete=django.db.models.deletion.CASCADE, to='hr_system.employer'),
            preserve_default=False,
        ),
    ]
