# Generated by Django 4.1.7 on 2023-03-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0004_employee_employer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyinventory',
            old_name='employer_id',
            new_name='emp_id',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='Employer',
            new_name='employer_name',
        ),
        migrations.RenameField(
            model_name='employer',
            old_name='Employer_id',
            new_name='employer_id',
        ),
    ]
