# Generated by Django 4.1.7 on 2023-03-01 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0006_alter_companyinventory_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinventory',
            name='employee_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_system.employee'),
        ),
    ]
