# Generated by Django 4.1.7 on 2023-03-03 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_system', '0007_companyinventory_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinventory',
            name='returning',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='companyinventory',
            name='taking',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_off_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='time_off_start',
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name='TimeOff',
            fields=[
                ('timeoff_id', models.AutoField(primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('comments', models.CharField(blank=True, max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
