# Generated by Django 4.1.7 on 2023-03-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0008_alter_companyinventory_returning_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr_system.employer'),
        ),
    ]
