# Generated by Django 4.1.7 on 2023-03-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0010_remove_employee_on_leave_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
