# Generated by Django 4.1.7 on 2023-03-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0011_alter_employee_dob_alter_employee_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
