# Generated by Django 4.1.7 on 2023-03-03 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr_system', '0017_employees_employeetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinventory',
            name='asset_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hr_system.companyasset'),
        ),
    ]
