# Generated by Django 4.1.7 on 2023-03-03 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_admin', '0002_employeetask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='employeetask',
            options={},
        ),
    ]
